/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinelligestionegite;

/**
 *
 * @author aureli.giulia
 */
public class FrmCreazioneGita extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCreazioneGita.class.getName());

    /**
     * Creates new form FrmCreazioneGita
     */
    public FrmCreazioneGita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCreazioneGita = new javax.swing.JPanel();
        btnIndietro = new javax.swing.JButton();
        btnAvanti = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        txtLuogo = new javax.swing.JTextField();
        btnCrea = new javax.swing.JButton();
        lblLuogo = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCreazioneGita = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCreazioneGita.setBackground(new java.awt.Color(153, 204, 255));

        btnIndietro.setBackground(new java.awt.Color(51, 153, 255));
        btnIndietro.setText("<");
        btnIndietro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAvanti.setBackground(new java.awt.Color(0, 153, 255));
        btnAvanti.setText(">");
        btnAvanti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtLuogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuogoActionPerformed(evt);
            }
        });

        btnCrea.setBackground(new java.awt.Color(51, 153, 255));
        btnCrea.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        btnCrea.setText("Crea");
        btnCrea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLuogo.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        lblLuogo.setForeground(new java.awt.Color(0, 0, 204));
        lblLuogo.setLabelFor(txtLuogo);
        lblLuogo.setText("Luogo:");

        lblData.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(0, 0, 204));
        lblData.setLabelFor(txtData);
        lblData.setText("Data:");

        tblCreazioneGita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCreazioneGita);

        javax.swing.GroupLayout pnlCreazioneGitaLayout = new javax.swing.GroupLayout(pnlCreazioneGita);
        pnlCreazioneGita.setLayout(pnlCreazioneGitaLayout);
        pnlCreazioneGitaLayout.setHorizontalGroup(
            pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreazioneGitaLayout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreazioneGitaLayout.createSequentialGroup()
                        .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLuogo)
                            .addComponent(lblData))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLuogo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCrea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(pnlCreazioneGitaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvanti, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pnlCreazioneGitaLayout.setVerticalGroup(
            pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreazioneGitaLayout.createSequentialGroup()
                .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlCreazioneGitaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCreazioneGitaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLuogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLuogo))
                        .addGap(44, 44, 44)
                        .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblData)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvanti)
                    .addComponent(btnIndietro))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCreazioneGita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCreazioneGita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLuogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCreazioneGita().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanti;
    private javax.swing.JButton btnCrea;
    private javax.swing.JButton btnIndietro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblLuogo;
    private javax.swing.JPanel pnlCreazioneGita;
    private javax.swing.JTable tblCreazioneGita;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtLuogo;
    // End of variables declaration//GEN-END:variables
}
