/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinelligestionegite;

import javax.swing.JOptionPane;

/**
 *
 * @author utente
 */
public class FrmFile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmFile.class.getName());
    private GestioneFile gF;
    /**
     * Creates new form FrmFile
     */
    public FrmFile() {
        initComponents();
        gF = new GestioneFile();
        contaRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCreazioneGita = new javax.swing.JPanel();
        btnIndietro = new javax.swing.JButton();
        btnAvanti = new javax.swing.JButton();
        btnSvuotaFile = new javax.swing.JButton();
        btnSalvaSuFile = new javax.swing.JButton();
        btnCaricaDaFile = new javax.swing.JButton();
        lblNRecordGite = new javax.swing.JLabel();
        lblNRecordStudenti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestione file");

        pnlCreazioneGita.setBackground(new java.awt.Color(153, 204, 255));

        btnIndietro.setBackground(new java.awt.Color(51, 153, 255));
        btnIndietro.setText("<");
        btnIndietro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroActionPerformed(evt);
            }
        });

        btnAvanti.setBackground(new java.awt.Color(0, 153, 255));
        btnAvanti.setText(">");
        btnAvanti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvantiActionPerformed(evt);
            }
        });

        btnSvuotaFile.setBackground(new java.awt.Color(51, 153, 255));
        btnSvuotaFile.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        btnSvuotaFile.setText("Svuota file");
        btnSvuotaFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSvuotaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSvuotaFileActionPerformed(evt);
            }
        });

        btnSalvaSuFile.setBackground(new java.awt.Color(51, 153, 255));
        btnSalvaSuFile.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        btnSalvaSuFile.setText("Salva su File");
        btnSalvaSuFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvaSuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaSuFileActionPerformed(evt);
            }
        });

        btnCaricaDaFile.setBackground(new java.awt.Color(51, 153, 255));
        btnCaricaDaFile.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        btnCaricaDaFile.setText("Carica da File");
        btnCaricaDaFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCaricaDaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaDaFileActionPerformed(evt);
            }
        });

        lblNRecordGite.setText(" ");
        lblNRecordGite.setToolTipText("");

        lblNRecordStudenti.setText(" ");
        lblNRecordStudenti.setToolTipText("");

        javax.swing.GroupLayout pnlCreazioneGitaLayout = new javax.swing.GroupLayout(pnlCreazioneGita);
        pnlCreazioneGita.setLayout(pnlCreazioneGitaLayout);
        pnlCreazioneGitaLayout.setHorizontalGroup(
            pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreazioneGitaLayout.createSequentialGroup()
                .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreazioneGitaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvaSuFile, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSvuotaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCaricaDaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCreazioneGitaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNRecordGite, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCreazioneGitaLayout.createSequentialGroup()
                                .addComponent(btnIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(btnAvanti, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNRecordStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlCreazioneGitaLayout.setVerticalGroup(
            pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreazioneGitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNRecordGite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNRecordStudenti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnCaricaDaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvaSuFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSvuotaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(pnlCreazioneGitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvanti)
                    .addComponent(btnIndietro))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCreazioneGita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCreazioneGita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroActionPerformed
        FrmVisualizza frmVisualizza = new FrmVisualizza();
        frmVisualizza.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIndietroActionPerformed

    private void btnAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvantiActionPerformed
        FrmCreazioneGita frmCreazioneGita = new FrmCreazioneGita();
        frmCreazioneGita.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvantiActionPerformed

    private void btnSvuotaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSvuotaFileActionPerformed
        gF.svuota();
        JOptionPane.showMessageDialog(null, "Il file e' stato svuotato.", "Informazione", JOptionPane.INFORMATION_MESSAGE);
        contaRecord();
    }//GEN-LAST:event_btnSvuotaFileActionPerformed

    private void btnSalvaSuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaSuFileActionPerformed
        gF.salvaSuFile();
        JOptionPane.showMessageDialog(null, "Tutti i dati sono stati salvati nel file.", "Informazione", JOptionPane.INFORMATION_MESSAGE);
        contaRecord();
    }//GEN-LAST:event_btnSalvaSuFileActionPerformed

    private void btnCaricaDaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaDaFileActionPerformed
        gF.caricaDaFile();
        JOptionPane.showMessageDialog(null, "Tutti i dati del file sono stati caricati.", "Informazione", JOptionPane.INFORMATION_MESSAGE);
        contaRecord();
    }//GEN-LAST:event_btnCaricaDaFileActionPerformed

    /**
     * Metodo che aggiorna le label per far vedere nRecord
     */
    public void contaRecord(){
        lblNRecordGite.setText("Nel file gite sono presenti " + gF.contaRecordGite() + " record");
        lblNRecordStudenti.setText("Nel file studenti sono presenti " + gF.contaRecordGite() + " record");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmFile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanti;
    private javax.swing.JButton btnCaricaDaFile;
    private javax.swing.JButton btnIndietro;
    private javax.swing.JButton btnSalvaSuFile;
    private javax.swing.JButton btnSvuotaFile;
    private javax.swing.JLabel lblNRecordGite;
    private javax.swing.JLabel lblNRecordStudenti;
    private javax.swing.JPanel pnlCreazioneGita;
    // End of variables declaration//GEN-END:variables
}
