/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinelligestionegite;

import javax.swing.JOptionPane;

/**
 *
 * @author aureli.giulia
 */
public class FrmVisualizza extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVisualizza.class.getName());

    /**
     * Creates new form FrmGite
     */
    public FrmVisualizza() {
        initComponents();
        //tuttu gli studenti vengono aggiunti alla combobox
        if(GestioneStudenti.getListaStudenti() != null){
            for(Studente s : GestioneStudenti.getListaStudenti()){
                cmbStudenti.addItem(s);
            }
        }
        //tutte le gite vengono aggiunte alla combobox
        if(GestioneGite.getListaGite() != null){
            for(Gita g : GestioneGite.getListaGite()){
                cmbGite.addItem(g);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVisualizza = new javax.swing.JPanel();
        btnVediStudenti = new javax.swing.JButton();
        btnVediGite = new javax.swing.JButton();
        cmbStudenti = new javax.swing.JComboBox<>();
        cmbGite = new javax.swing.JComboBox<>();
        btnIndietro = new javax.swing.JButton();
        btnAvanti = new javax.swing.JButton();
        lblLuogo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnIscrivi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaVisualizza = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visualizza");

        pnlVisualizza.setBackground(new java.awt.Color(153, 204, 255));

        btnVediStudenti.setBackground(new java.awt.Color(51, 153, 255));
        btnVediStudenti.setFont(new java.awt.Font("Sitka Subheading", 3, 12)); // NOI18N
        btnVediStudenti.setText("Vedi studenti iscritti");
        btnVediStudenti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVediStudenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVediStudentiActionPerformed(evt);
            }
        });

        btnVediGite.setBackground(new java.awt.Color(51, 153, 255));
        btnVediGite.setFont(new java.awt.Font("Sitka Subheading", 3, 12)); // NOI18N
        btnVediGite.setText("Vedi Gite scelte");
        btnVediGite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVediGite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVediGiteActionPerformed(evt);
            }
        });

        btnIndietro.setBackground(new java.awt.Color(51, 153, 255));
        btnIndietro.setText("<");
        btnIndietro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroActionPerformed(evt);
            }
        });

        btnAvanti.setBackground(new java.awt.Color(0, 153, 255));
        btnAvanti.setText(">");
        btnAvanti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvantiActionPerformed(evt);
            }
        });

        lblLuogo.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        lblLuogo.setForeground(new java.awt.Color(0, 0, 204));
        lblLuogo.setLabelFor(lblLuogo);
        lblLuogo.setText("Luogo");

        lblNome.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 204));
        lblNome.setLabelFor(lblNome);
        lblNome.setText("Nome");

        btnIscrivi.setBackground(new java.awt.Color(51, 153, 255));
        btnIscrivi.setFont(new java.awt.Font("Sitka Subheading", 3, 12)); // NOI18N
        btnIscrivi.setText("Iscrivi studente alla gita");
        btnIscrivi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIscrivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIscriviActionPerformed(evt);
            }
        });

        txaVisualizza.setEditable(false);
        txaVisualizza.setColumns(20);
        txaVisualizza.setRows(5);
        jScrollPane2.setViewportView(txaVisualizza);

        javax.swing.GroupLayout pnlVisualizzaLayout = new javax.swing.GroupLayout(pnlVisualizza);
        pnlVisualizza.setLayout(pnlVisualizzaLayout);
        pnlVisualizzaLayout.setHorizontalGroup(
            pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisualizzaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvanti, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisualizzaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVediGite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVediStudenti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(cmbGite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbStudenti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNome)
                    .addComponent(lblLuogo)
                    .addComponent(btnIscrivi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlVisualizzaLayout.setVerticalGroup(
            pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisualizzaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlVisualizzaLayout.createSequentialGroup()
                        .addComponent(lblLuogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(btnIscrivi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnVediGite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnVediStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvanti)
                    .addComponent(btnIndietro))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVisualizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVisualizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroActionPerformed
        FrmCreazioneStudente frmCreazioneStudente = new FrmCreazioneStudente();
        frmCreazioneStudente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIndietroActionPerformed

    private void btnAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvantiActionPerformed
        FrmFile frmFile = new FrmFile();
        frmFile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvantiActionPerformed

    private void btnIscriviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIscriviActionPerformed
        Studente s = (Studente)cmbStudenti.getSelectedItem();
        Gita g = (Gita)cmbGite.getSelectedItem();
        //controllo per vedere se entrambe le combobox hanno un elemento selezionato
        if(s == null || g == null) return;
        //iscrizione e scrittura messaggio
        if(s.iscrivi(g))JOptionPane.showMessageDialog(null, s.getNome() + " " + s.getCognome() + " e' stato iscritto alla gita di " + g.getLocalita() + " del " + g.getData(), "Informazione", JOptionPane.INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(null, s.getNome() + " " + s.getCognome() + " e' gia' iscritto alla gita di " + g.getLocalita() + " del " + g.getData(), "Informazione", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnIscriviActionPerformed

    private void btnVediGiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVediGiteActionPerformed
        //si azzera il testo
        txaVisualizza.setText("");
        Studente s = (Studente)cmbStudenti.getSelectedItem();
        //controllo per vedere se uno studente e' selezionato
        if(s == null) return;
        //scrittura testo
        txaVisualizza.append("Gite a cui partecipa " + s.getNome() + " " + s.getCognome() + ": \n");
        for(Gita g : GestioneGite.cercaGitePerStudente(s)){
            txaVisualizza.append("-" + g.toString() + "\n");
        }
    }//GEN-LAST:event_btnVediGiteActionPerformed

    private void btnVediStudentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVediStudentiActionPerformed
        //si azzera il testo
        txaVisualizza.setText("");
        Gita g = (Gita)cmbGite.getSelectedItem();
        //controllo per vedere se una gita e' selezionata
        if(g == null) return;
        //scrittura testo
        txaVisualizza.append("Studenti che partecipano alla gita di " + g.getLocalita() + " del " + g.getData() + ": \n");
        for(Studente s : GestioneStudenti.cercaStudentiPerGita(g)){
          txaVisualizza.append("-" + s.toString() + "\n");  
        }
    }//GEN-LAST:event_btnVediStudentiActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmVisualizza().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanti;
    private javax.swing.JButton btnIndietro;
    private javax.swing.JButton btnIscrivi;
    private javax.swing.JButton btnVediGite;
    private javax.swing.JButton btnVediStudenti;
    private javax.swing.JComboBox<Gita> cmbGite;
    private javax.swing.JComboBox<Studente> cmbStudenti;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLuogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlVisualizza;
    private javax.swing.JTextArea txaVisualizza;
    // End of variables declaration//GEN-END:variables
}
