/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurelimartinelligestionegite;

/**
 *
 * @author aureli.giulia
 */
public class FrmVisualizza extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVisualizza.class.getName());

    /**
     * Creates new form FrmGite
     */
    public FrmVisualizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVisualizza = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizza = new javax.swing.JTable();
        btnStudenti = new javax.swing.JButton();
        btnGite = new javax.swing.JButton();
        cmbGite = new javax.swing.JComboBox<>();
        cmbStudenti = new javax.swing.JComboBox<>();
        btnIndietro = new javax.swing.JButton();
        btnAvanti = new javax.swing.JButton();
        lblLuogo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVisualizza.setBackground(new java.awt.Color(153, 204, 255));

        tblVisualizza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVisualizza);

        btnStudenti.setBackground(new java.awt.Color(51, 153, 255));
        btnStudenti.setFont(new java.awt.Font("Sitka Subheading", 3, 12)); // NOI18N
        btnStudenti.setText("Vedi studenti iscritti");
        btnStudenti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGite.setBackground(new java.awt.Color(51, 153, 255));
        btnGite.setFont(new java.awt.Font("Sitka Subheading", 3, 12)); // NOI18N
        btnGite.setText("Vedi Gite scelte");
        btnGite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbGite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alessandra" }));

        cmbStudenti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Città di Castello" }));
        cmbStudenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudentiActionPerformed(evt);
            }
        });

        btnIndietro.setBackground(new java.awt.Color(51, 153, 255));
        btnIndietro.setText("<");
        btnIndietro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAvanti.setBackground(new java.awt.Color(0, 153, 255));
        btnAvanti.setText(">");
        btnAvanti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLuogo.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        lblLuogo.setForeground(new java.awt.Color(0, 0, 204));
        lblLuogo.setLabelFor(lblLuogo);
        lblLuogo.setText("Luogo");

        lblNome.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 204));
        lblNome.setLabelFor(lblNome);
        lblNome.setText("Nome");

        javax.swing.GroupLayout pnlVisualizzaLayout = new javax.swing.GroupLayout(pnlVisualizza);
        pnlVisualizza.setLayout(pnlVisualizzaLayout);
        pnlVisualizzaLayout.setHorizontalGroup(
            pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisualizzaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStudenti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(cmbStudenti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbGite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNome)
                    .addComponent(lblLuogo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(pnlVisualizzaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvanti, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        pnlVisualizzaLayout.setVerticalGroup(
            pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisualizzaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlVisualizzaLayout.createSequentialGroup()
                        .addComponent(lblLuogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnGite, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStudenti, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlVisualizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvanti)
                    .addComponent(btnIndietro))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVisualizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVisualizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStudentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudentiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStudentiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmVisualizza().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanti;
    private javax.swing.JButton btnGite;
    private javax.swing.JButton btnIndietro;
    private javax.swing.JButton btnStudenti;
    private javax.swing.JComboBox<String> cmbGite;
    private javax.swing.JComboBox<String> cmbStudenti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLuogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlVisualizza;
    private javax.swing.JTable tblVisualizza;
    // End of variables declaration//GEN-END:variables
}
